version: '3'
services:
  database:
    image: postgres:10.5-alpine
    ports:
      - 5432:5432
    volumes:
      - databasedata:/var/lib/postgresql/data
    env_file:
      - variables.env
volumes:
  databasedata:
networks:
  default:
    external:
      name: siganet

